### PR TITLE
Retry image deletion incase deletion fails due to conflict

### PR DESCRIPTION
**Pull request by rajivmucheli**
1. introduces max_retries=3, retry_delay=5
2. Follow up on https://bugs.launchpad.net/python-swiftclient/+bug/1899495

The below exception is resolved :

```
ClientException
Container DELETE failed: https://XXX 409 Conflict [first 60 chars of response] b'<html><h1>Conflict</h1><p>There was a conflict when trying t' (txn: XXX)
```

### CODE REVIEW

**Comment by rajivmucheli** [comment]
i am unable to share the estimates, would it help if change max_retries=2, retry_delay=3 ?

also from a if to a while clause ?

**Comment by fwiesel** [comment]
I'd go with `retry_delay=0.5` and `max_retries=20`  or something. It doesn't cost much to retry more often, but for the client it looks more responsive.

**Review by fwiesel — CHANGES_REQUESTED** [review]
Please specify the specific exception.
This will catch anything, including syntax errors.

**Review by fwiesel — APPROVED** [review]
Good enough, I would say.

Ideally you would also check the http-status code (https://github.com/openstack/python-swiftclient/blob/master/swiftclient/exceptions.py#L32C14-L32C25).

I.e. we probably do not want to retry on permission errors, possibly others.
Retrying on internal server errors would probably be okay.

**Comment by rajivmucheli** [comment]
i tried based on : `e.http_status == http.client.CONFLICT` but it did not work.

**Pull request merged**
